In [1]:
import torch
import numpy as np
import pandas as pd

In [7]:
random_int = torch.randint(low=0, high=10, size=(2, 3))
print("Random Integer Tensor:\n", random_int)
template = torch.randint(low=0, high=10, size=(10, 10))
print("Random Integer Tensor:\n", template)
random_int_like = torch.randint_like(template, low=0, high=2, dtype=torch.int64)
print("Random Integer Tensor Like Template:\n", random_int_like)

Random Integer Tensor:
 tensor([[2, 2, 0],
        [1, 9, 0]])
Random Integer Tensor:
 tensor([[9, 7, 0, 7, 1, 2, 1, 2, 4, 6],
        [7, 6, 2, 4, 4, 7, 9, 0, 5, 0],
        [7, 1, 4, 4, 0, 0, 8, 0, 0, 0],
        [3, 2, 3, 5, 5, 3, 3, 2, 7, 4],
        [3, 6, 0, 8, 5, 8, 3, 8, 0, 9],
        [5, 3, 4, 4, 0, 4, 8, 9, 8, 1],
        [8, 9, 8, 6, 0, 0, 3, 7, 1, 3],
        [8, 3, 4, 1, 9, 7, 5, 0, 9, 8],
        [4, 7, 4, 3, 0, 0, 1, 7, 1, 6],
        [0, 8, 3, 0, 8, 1, 0, 6, 4, 2]])
Random Integer Tensor Like Template:
 tensor([[0, 1, 1, 0, 1, 1, 0, 1, 0, 1],
        [0, 0, 0, 1, 1, 0, 0, 0, 1, 1],
        [0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 0, 0, 1, 0],
        [0, 1, 0, 1, 0, 0, 1, 1, 0, 1],
        [0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
        [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 0, 0, 1, 0, 0, 1, 1, 1],
        [0, 0, 1, 1, 1, 1, 0, 1, 0, 1],
        [1, 0, 1, 1, 1, 1, 0, 0, 1, 0]])


In [8]:
# Create a 3x4 tensor
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get a single element at row 1, column 2
single_element_tensor = x[1, 2]

print("\nINDEXING SINGLE ELEMENT AT [1, 2]:", single_element_tensor)
print("-" * 55)

# Get the entire second row (index 1)
second_row = x[1]

print("\nINDEXING ENTIRE ROW [1]:", second_row)
print("-" * 55)

# Last row
last_row = x[-1]

print("\nINDEXING ENTIRE LAST ROW ([-1]):", last_row, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 2]: tensor(7)
-------------------------------------------------------

INDEXING ENTIRE ROW [1]: tensor([5, 6, 7, 8])
-------------------------------------------------------

INDEXING ENTIRE LAST ROW ([-1]): tensor([ 9, 10, 11, 12]) 



In [10]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Get the first two rows
first_two_rows = x[0:2]

print("\nSLICING FIRST TWO ROWS ([0:2]):\n\n", first_two_rows)
print("-" * 55)

# Get the third column of all rows
third_column = x[:, 2]

print("\nSLICING THIRD COLUMN ([:, 2]]):", third_column)
print("-" * 55)

# Every other column
every_other_col = x[:, ::2]

print("\nEVERY OTHER COLUMN ([:, ::2]):\n\n", every_other_col)
print("-" * 55)

# Last column
last_col = x[:, -1]

print("\nLAST COLUMN ([:, -1]):", last_col, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

SLICING FIRST TWO ROWS ([0:2]):

 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
-------------------------------------------------------

SLICING THIRD COLUMN ([:, 2]]): tensor([ 3,  7, 11])
-------------------------------------------------------

EVERY OTHER COLUMN ([:, ::2]):

 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
-------------------------------------------------------

LAST COLUMN ([:, -1]): tensor([ 4,  8, 12]) 



In [ ]:
weights = None
weights = torch.tensor([0.6, 0.4,0.2])
print("weights DATA SHAPE UNSQUEEZE:", weights.shape)
print("weights UNSQUEEZE DATA:", weights)
print("-" * 45)
#Dimension Addition using unsqueeze 0 is row [[0.6000, 0.4000, 0.2000]], 1 is column [[0.6000],[0.4000],[0.2000]].  Note the extra brackets with unsqueeze
weights_unsqueeze = weights.unsqueeze(1)
print("weights_unsqueeze DATA SHAPE UNSQUEEZE:", weights_unsqueeze.shape)
print("weights_unsqueeze UNSQUEEZE DATA:", weights_unsqueeze)
print("-" * 45)

weights DATA SHAPE UNSQUEEZE: torch.Size([3])
weights UNSQUEEZE DATA: tensor([0.6000, 0.4000, 0.2000])
---------------------------------------------
weights_unsqueeze DATA SHAPE UNSQUEEZE: torch.Size([3, 1])
weights_unsqueeze UNSQUEEZE DATA: tensor([[0.6000],
        [0.4000],
        [0.2000]])
---------------------------------------------


In [24]:
x = torch.tensor([2.0, 4.0, 6.0])
y = torch.tensor([1.0, 2.0, 3.0])
result = x / y + 5
print(result)

tensor([7., 7., 7.])


In [34]:
x = torch.tensor([25.0])
print(x)
print(x.shape)
x = x.unsqueeze(0)
print(x)
print(x.shape)
x = x.squeeze()
print(x)
print(x.shape)

tensor([25.])
torch.Size([1])
tensor([[25.]])
torch.Size([1, 1])
tensor(25.)
torch.Size([])


You're getting `torch.Size([])` (a scalar) at the end because of how `squeeze()` works - it removes **all** dimensions of size 1.

Let me trace through your code:

```python
x = torch.tensor([25.0])
print(x)        # tensor([25.])
print(x.shape)  # torch.Size([1]) - 1D tensor with 1 element

x = x.unsqueeze(0)
print(x)        # tensor([[25.]]) 
print(x.shape)  # torch.Size([1, 1]) - 2D tensor (1 row, 1 column)

x = x.squeeze()
print(x)        # tensor(25.)
print(x.shape)  # torch.Size([]) - 0D tensor (scalar)
```

## Why this happens:

- `squeeze()` **removes ALL dimensions of size 1**
- Your tensor had shape `[1, 1]` - both dimensions are size 1
- So `squeeze()` removed both, leaving a scalar (0D tensor)

## Solutions:

**If you want to keep it 1D:**
```python
x = x.squeeze(0)  # Only squeeze dimension 0
# Result: torch.Size([1])
```

**Or:**
```python
x = x.squeeze().unsqueeze(0)  # Squeeze all, then add back one dimension
# Result: torch.Size([1])
```

**Key takeaway:** `squeeze()` with no arguments is aggressive - it removes **every** dimension of size 1. Use `squeeze(dim)` if you want to remove only a specific dimension.